version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/email_svc
hooks:
  ApplicationStop:
    - location: ./scripts/stop_server.sh
      runas: root
  AfterInstall:
    - location: ./scripts/install_app_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./scripts/start_server
      runas: root
